apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: spring-boot-amq-configmap
data:
  application.properties: |-
    broker.name: ${KUBERNETES_NAME}
    broker.dataDirectory: /mnt/${KUBERNETES_NAME}
    broker.network.url: kube://spring-boot-amq:61616/?transportType=tcp
    broker.ssl.keyStore: file:/etc/secret/broker.ks